//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UVSproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public long Id { get; set; }
        public string DiscountCode { get; set; }
        public long ProductId { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
